maidsafe/safe-authenticator-mobile

- SafeAuthenticator/Helpers/MessengerConstants.cs
- SafeAuthenticator/Models/ObservableRangeCollection.cs
- SafeAuthenticator/Services/AuthService.cs
- SafeAuthenticator/ViewModels/AppInfoViewModel.cs
- SafeAuthenticator/ViewModels/HomeViewModel.cs
- SafeAuthenticator/Views/AppInfoPage.xaml.cs
- Tests/SafeAuth.Tests/ContainerTest.cs
- Tests/SafeAuth.Tests/Utils.cs
fixes [#3](https://github.com/maidsafe/safe-authenticator-mobile/issues/6)
Add feature to revoke permission provided to an application
> Revoke permission 

- SafeAuthenticator/Controls/Converters/ByteArraytoHexStringConverter.cs
- SafeAuthenticator/Helpers/UrlFormat.cs
- SafeAuthenticator/Models/ModelHelpers.cs
- SafeAuthenticator/Models/ResponseEventArgs.cs
- SafeAuthenticator/SafeAuthenticator.csproj
- SafeAuthenticator/Services/AuthService.cs
- SafeAuthenticator/ViewModels/HomeViewModel.cs
- SafeAuthenticator/ViewModels/RequestDetailViewModel.cs
- SafeAuthenticator/Views/RequestDetailPage.xaml
- SafeAuthenticator/Views/RequestDetailPage.xaml.cs
Fixes: #21 
**Changes**
- Added support for Unregistered Request
- Added support for Container Request
- Added support for ShareMD Request
- Detailed Request Page
> Extend Request Support 

- SafeAuthenticator/Helpers/Utilities.cs
- SafeAuthenticator/Services/AuthService.cs
- SafeAuthenticator/ViewModels/AppInfoViewModel.cs
- SafeAuthenticator/ViewModels/HomeViewModel.cs
- Pull to refersh on homePage
- Revoke permission button clicked
> fix/SafeAuth: display proper error message

- SafeAuthenticator/Views/RequestDetailPage.xaml
fixes: #37 
**Changes: **
Switch permission buttons in permissions dialog.
> Switch permission (allow, deny) buttons

- SafeAuthenticator/Views/RequestDetailPage.xaml
> Show no permission text when no container permission requested.

- SafeAuthenticator/Controls/ContainerPermissionViewCell.xaml
- SafeAuthenticator/Controls/MDataPermissionViewCell.xaml
- SafeAuthenticator/Controls/RegisteredAppViewCell.xaml
- SafeAuthenticator/Views/AppInfoPage.xaml
fixes [#53](https://github.com/maidsafe/safe-authenticator-mobile/issues/53)
Refer [this](https://github.com/maidsafe/safe-authenticator-mobile/issues/53#issuecomment-462808923) comment for details
> Disable tap animation of listview in AppInfoPage

- SafeAuthenticator/ViewModels/SettingsViewModel.cs
fixes #76 
- Add the native progress dialog dependency service `NativeProgressDialog.ShowNativeDialog()` to show the loading state with the message "Logging out".
- This progress will be displayed if there is a delay in logout, progress will not be shown if there is very minimal delay.
> Display the Loading state for Logout

- SafeAuthenticator.iOS/SafeAuthenticator.iOS.csproj
Fixes #82 
Update linker behavior on iOS to `Don't link`
> Update linker behavior on iOS

- SafeAuthenticator/ViewModels/HomeViewModel.cs
- SafeAuthenticator/ViewModels/RequestDetailViewModel.cs
- SafeAuthenticator/ViewModels/SettingsViewModel.cs
- SafeAuthenticator/Views/HomePage.xaml
Following changes are made
- Add the internet connection check before fetching account info in the settings page.
- Add the internet connection check before refreshing registered app list on the home page.
- Handle unregistered app request.
> Add internet connection check and handle unregistered app request

- SafeAuthenticator/ViewModels/AppInfoViewModel.cs
Add internet connection check before revoking the app in `AppInfoPage`
> Add internet connection check in appinfo page

- SafeAuthenticator/Controls/CreateAcctPage/CreateAcctStep1.xaml
- SafeAuthenticator/Controls/CreateAcctPage/CreateAcctStep1.xaml.cs
Fixes #97 
Add a tap animation using XamEffects for Android, and add a fade animation for iOS.
> Add tap animation for paste icon in CreateAcctPage

- SafeAuthenticator/App.xaml
- SafeAuthenticator/Controls/Converters/HtmlLabelConverter.cs
- SafeAuthenticator/Controls/CreateAcctPage/CreateAcctStep1.xaml.cs
- SafeAuthenticator/Helpers/Constants.cs
- SafeAuthenticator/Helpers/Utilities.cs
- SafeAuthenticator/Services/AuthService.cs
- SafeAuthenticator/ViewModels/CreateAcctViewModel.cs
- SafeAuthenticator/ViewModels/HomeViewModel.cs
- SafeAuthenticator/ViewModels/LoginViewModel.cs
- SafeAuthenticator/ViewModels/RequestDetailViewModel.cs
- SafeAuthenticator/ViewModels/SettingsViewModel.cs
- SafeAuthenticator/Views/RequestDetailPage.xaml
- SafeAuthenticator/Views/SettingsPage.xaml
Fixes #109 
- Fix paste icon in CreateAcctPage
- Fix authorization popup padding
- Use global constants for URLs
- Handle scenarios where multiple alerts are displayed
> Paste Icon bug

- SafeAuthenticator/Services/AuthService.cs
- SafeAuthenticator/Views/RequestDetailPage.xaml
When a container request is sent to the authentication when there is no internet connection, the error message displayed is not user-friendly.
> update error message displayed on IpcReqError

- CHANGELOG.md
- SafeAuthenticator.Android/Properties/AndroidManifest.xml
- SafeAuthenticator.iOS/Info.plist
- Update `changelog` file for v0.1.1 
- update version no to `0.1.1` on `AndroidManifest.xml` and `Info.plist` for Android and iOS respectively
> Update changelog file

- SafeAuthenticator.Android/Helpers/AndroidNativeBrowserService.cs
- SafeAuthenticator/App.xaml
- SafeAuthenticator/Services/AuthService.cs
- SafeAuthenticator/ViewModels/SettingsViewModel.cs
- SafeAuthenticator/Views/RequestDetailPage.xaml
- SafeAuthenticator/Views/SettingsPage.xaml
- SafeAuthenticator/Views/SettingsPage.xaml.cs
> Fix support on Andorid when API level<23

- CHANGELOG.md
- SafeAuthenticator.Android/Properties/AndroidManifest.xml
- SafeAuthenticator.iOS/Info.plist
Update version from `0.1.1` to `0.1.2`
> docs/version: Update version to 0.1.2

- README.md
- codeowners
**Changes**
- Added more content in README file
**Preview**
https://github.com/ravinderjangra/safe-authenticator-https://github.com/ravinderjangra/safe-authenticator-mobile/blob/update-readme/README.md
> docs/README: update README to add more documentation

- SafeAuthenticator/Helpers/Constants.cs
- SafeAuthenticator/Helpers/Utilities.cs
- SafeAuthenticator/ViewModels/HomeViewModel.cs
> fix/AuthorizationPopup: Handle invalid container names

- SafeAuthenticator.Android/Helpers/AppHandler.cs
- SafeAuthenticator.Android/MainActivity.cs
- SafeAuthenticator.Android/SafeAuthenticator.Android.csproj
- SafeAuthenticator.iOS/Helpers/AppHandler.cs
- SafeAuthenticator.iOS/SafeAuthenticator.iOS.csproj
- SafeAuthenticator/Services/IAppHandler.cs
- SafeAuthenticator/ViewModels/RequestDetailViewModel.cs
> fix/SafeAuth: Handle error when app uri not found

- SafeAuthenticator/Helpers/Constants.cs
- SafeAuthenticator/Services/AuthService.cs
- SafeAuthenticator/ViewModels/AppInfoViewModel.cs
- SafeAuthenticator/ViewModels/HomeViewModel.cs
> feat/appRevocation: Flush revoke queue

- SafeAuthenticator/Helpers/Utilities.cs
> fix/SafeAuth: update error message for invalid app container

- CHANGELOG.md
- SafeAuthenticator.Android/Properties/AndroidManifest.xml
- SafeAuthenticator.iOS/Info.plist
Update version from `0.1.2` to `0.1.3`
> version change: Update version to 0.1.3

- CakeScripts/NativeLibs.cake
- SafeAuthenticator/Controls/TestSafeCoinPermissions.xaml
- SafeAuthenticator/Controls/TestSafeCoinPermissions.xaml.cs
- SafeAuthenticator/Native/Authenticator.cs
- SafeAuthenticator/Native/IAuthBindings.cs
- SafeAuthenticator/PlatformSpecific/AuthBindings.cs
- SafeAuthenticator/SafeAuthenticator.csproj
- SafeAuthenticator/ViewModels/RequestDetailViewModel.cs
- SafeAuthenticator/Views/RequestDetailPage.xaml
- Tests/SafeAuth.Tests/CreateAccountTest.cs
> Show test coin permissions

- SafeAuthenticator.Android/MainActivity.cs
- SafeAuthenticator.Android/SafeAuthenticator.Android.csproj
- SafeAuthenticator.iOS/AppDelegate.cs
- SafeAuthenticator.iOS/SafeAuthenticator.iOS.csproj
- SafeAuthenticator/Models/VaultConnectionFile.cs
- SafeAuthenticator/SafeAuthenticator.csproj
- SafeAuthenticator/Services/VaultConnectionFileManager.cs
- SafeAuthenticator/ViewModels/VaultConnectionFileViewModel.cs
- SafeAuthenticator/Views/LoginPage.xaml.cs
- SafeAuthenticator/Views/SettingsPage.xaml.cs
- SafeAuthenticator/Views/VaultConnectionFilePage.xaml
> Use radio button based list + other refactoring changes based on the discussion

- CakeScripts/NativeLibs.cake
- SafeAuthenticator/Models/RegisteredAppModel.cs
- SafeAuthenticator/Native/AuthTypes.cs
- SafeAuthenticator/Services/AuthService.cs
- SafeAuthenticator/ViewModels/AppInfoViewModel.cs
- SafeAuthenticator/ViewModels/HomeViewModel.cs
- SafeAuthenticator/Views/AppInfoPage.xaml
- SafeAuthenticator/Views/HomePage.xaml
fixes: #165 
**After Changes**
_**Note:** Android CI will fail because of a missing certificate_
> feat: Show AppPermissions on the app info page

- SafeAuthenticator/Services/VaultConnectionFileManager.cs
- SafeAuthenticator/ViewModels/VaultConnectionFileViewModel.cs
**Changes:**
- Fixes vault file storing issue on Android
> fix/filepicker: read the content only once and use that to store the file

- SafeAuthenticator/Helpers/Constants.cs
- SafeAuthenticator/Helpers/Utilities.cs
> refactor/login: show different login msg

- SafeAuthenticator/ViewModels/VaultConnectionFileViewModel.cs
- SafeAuthenticator/Views/VaultConnectionFilePage.xaml
_**Note:** It's still not generic enough. Also, text content can be improved._
> feat/vault: show MaidSafe vault download option

- README.md
- SafeAuthenticator.sln
- SafeAuthenticator/ViewModels/VaultConnectionFileViewModel.cs
- SafeAuthenticator/Views/LoginPage.xaml.cs
- SafeAuthenticator/Views/SettingsPage.xaml
- SafeAuthenticator/Views/SettingsPage.xaml.cs
- SafeAuthenticator/Views/VaultConnectionFilePage.xaml
- SafeAuthenticator/log.toml
fixes: #217 
The PR basically updates most of the text related to the `Choose a network` section. I think this can be further simplified.
> refactor/network: update text to use network instead of vault

- README.md
- get_release_description.sh
Also updated some readme references from `SAFE` to `Safe`
> chore(deps): update to reference renamed sn_api and sn_cli
