SafeAuthenticator.Android/Properties/AndroidManifest.xml
SafeAuthenticator.Android/SafeAuthenticator.Android.csproj
SafeAuthenticator.iOS/SafeAuthenticator.iOS.csproj
SafeAuthenticator/SafeAuthenticator.csproj
Tests/SafeAuth.Tests.Android/Properties/AndroidManifest.xml
Tests/SafeAuth.Tests.Android/SafeAuth.Tests.Android.csproj
Tests/SafeAuth.Tests.IOS/SafeAuth.Tests.IOS.csproj

fixes [#3](https://github.com/maidsafe/safe-authenticator-mobile/issues/4)
- Use the latest featues of xamarin.forms and make the app compatible with devices running the latest versions of android and iOS
- Update the CI (AzueDevOps) to run tests on the latest version of android and iOS

Update packages to support Android 9.0 and iOS 12.1

---

CakeScripts/NativeLibs.cake

- Use http download instead of using curl for downloading required libs from S3
- **Cake.Curl** requires curl to installed by default

CakeScript: Use http download instead of curl

---

SafeAuthenticator.Android/Properties/AndroidManifest.xml
SafeAuthenticator/Helpers/Utilities.cs
SafeAuthenticator/ViewModels/CreateAcctViewModel.cs
SafeAuthenticator/ViewModels/LoginViewModel.cs
SafeAuthenticator/Views/CreateAcctPage.xaml
SafeAuthenticator/Views/LoginPage.xaml

fixes [#25](https://github.com/maidsafe/safe-authenticator-mobile/issues/25)
display appropriate error messages instead of displaying the error code

Provide appropriate error message

---

SafeAuthenticator/App.xaml.cs
SafeAuthenticator/Helpers/AppConstants.cs
SafeAuthenticator/Helpers/Constants.cs
SafeAuthenticator/Helpers/Utilities.cs
SafeAuthenticator/Services/AuthService.cs
SafeAuthenticator/ViewModels/CreateAcctViewModel.cs
SafeAuthenticator/ViewModels/RequestDetailViewModel.cs
SafeAuthenticator/Views/RequestDetailPage.xaml
SafeAuthenticator/Views/RequestDetailPage.xaml.cs

fixes [#55](https://github.com/maidsafe/safe-authenticator-mobile/issues/55)
Handle the following scenarios in an authentication popup, 
- Displaying the popup with all the details of the requester app
After the user allow/deny the request
- Display a loading state 
after which the response is sent back to requester app, and in case we have an error
- Display the error message to the user

Handle delay after authentication request popup

---

SafeAuthenticator.Android/Helpers/MaterialEntryRenderer.cs
SafeAuthenticator.iOS/Helpers/MaterialEntryRenderer.cs
SafeAuthenticator.iOS/SafeAuthenticator.iOS.csproj
SafeAuthenticator/App.xaml
SafeAuthenticator/Controls/InvitationTokenEntryView.xaml
SafeAuthenticator/Controls/InvitationTokenEntryView.xaml.cs
SafeAuthenticator/Controls/MaterialEntry.cs
SafeAuthenticator/SafeAuthenticator.csproj
SafeAuthenticator/Views/CreateAcctPage.xaml

fixes[#50](https://github.com/maidsafe/safe-authenticator-mobile/issues/50)
-added a box view under the entry and paste icon which will bring the icon inside invitation token entry.
-created a property in the material entry to make the underline transparent.
-created a new content view for the invitation entry along with the paste button in it as a grid.
-created a data trigger for changing the color of the box view when there is a focus in the entry.

Add paste icon inside invitation token entry

---

SafeAuthenticator/Views/SettingsPage.xaml

Resolves #61 
The TapGestureRecognizer command binding set for the FAQ link in `SettingsPage` is not valid. Rename `FAQCommand` to `FaqCommand` in `SettingsPage`

Fix FAQ link in SettingsPage

---

SafeAuthenticator/App.xaml.cs
SafeAuthenticator/Helpers/Constants.cs
SafeAuthenticator/ViewModels/TutorialViewModel.cs

Fixes: #63  
Display the `TutorialPage` as the launch page of the app unless the user skips the tutorial by clicking `Skip` or he completes the tutorial by clicking `Login`/ `Create Account` button.

Display TutorialPage as launch page unless its skiped or completed

---

SafeAuthenticator.Android/MainActivity.cs
SafeAuthenticator.Android/SafeAuthenticator.Android.csproj
SafeAuthenticator.iOS/AppDelegate.cs
SafeAuthenticator.iOS/SafeAuthenticator.iOS.csproj
SafeAuthenticator/SafeAuthenticator.csproj
SafeAuthenticator/Views/SettingsPage.xaml

Fixes #68 
Use [XamEffects](https://github.com/mrxten/XamEffects) to add tap animation to external links (FAQ and Privacy policy) in SettingsPage.
**Tap animation in Android and iOS**

Add tap animation for external links in SettingsPage

---

SafeAuthenticator.Android/Helpers/AndroidNativeProgressDialogService.cs
SafeAuthenticator.Android/MainActivity.cs
SafeAuthenticator.Android/SafeAuthenticator.Android.csproj
SafeAuthenticator.iOS/Helpers/AppleNativeProgressDialogService.cs
SafeAuthenticator.iOS/SafeAuthenticator.iOS.csproj
SafeAuthenticator/Controls/DisposableAction.cs
SafeAuthenticator/Controls/INativeProgressDialogService.cs
SafeAuthenticator/Models/DisposableAction.cs
SafeAuthenticator/SafeAuthenticator.csproj
SafeAuthenticator/Services/AuthService.cs
SafeAuthenticator/ViewModels/AppInfoViewModel.cs
SafeAuthenticator/ViewModels/BaseViewModel.cs
SafeAuthenticator/ViewModels/CreateAcctViewModel.cs
SafeAuthenticator/ViewModels/LoginViewModel.cs

fixes[#52](https://github.com/maidsafe/safe-authenticator-mobile/issues/52)
- Added a dependency service for displaying the progress dialog natively.
- Implemented native Android progress dialog in SafeAuthenticator.Android.
- Implemented iOS native progress using BTProgressHUD custom progress dialog in SafeAuthenticator.iOS.
- Added a separate class for Disposable action to make the dialog disposable.
- Removed the Third party ACR dialog NuGet package.
Screen Shots
*Android*
*iOS*

Display progress dialogs natively for Android and iOS

---

SafeAuthenticator/Helpers/Constants.cs
SafeAuthenticator/Services/AuthService.cs
SafeAuthenticator/ViewModels/HomeViewModel.cs

fixes [#9](https://github.com/maidsafe/safe-authenticator-mobile/issues/9)
Cater to the following scenarios:
- Authentication request: 
- When an authentication request is sent by an app which has not been registered yet (or previously revoked), all containers and their respective permissions which are requested are added.
- When an authentication request is sent by an app which has already been registered, the request isn't capable of adding new containers or modifying the permissions of existing containers 
- App's own container can be added at any time by an authentication request
- Container request: 
- New containers may be added and permissions for the existing container may be modified by any container request   
- App's own container cannot be added or modified by a container …

Update registered applist manually before sending authentication response

---

SafeAuthenticator/Views/AppInfoPage.xaml
SafeAuthenticator/Views/LoginPage.xaml
SafeAuthenticator/Views/TutorialPage.xaml

Fixes #62 #59  
- Disable title in LoginPage, this will prevent the Login page title from being shown for fraction of a second and disappearing, when we click back button from `Create Account` page
- Set the `BackButtonTitle` property as `Login` in `TutorialPage` this will prevent the back button's title from changing when navigating from feature screens in iOS

Login page title is shown for fraction of a second and disappears

---

SafeAuthenticator/Views/LoginPage.xaml

fixes #69 
- Change the font size of "Need any help!" to avoid cropping.
- Add height request to increase the clickable area of the label.

 Add height to label to avoid cropping and to increase clickable area

---

SafeAuthenticator/App.xaml
SafeAuthenticator/Views/AppInfoPage.xaml

Fixes #67 
Use the following sizes for iOS
- Small: 14
- Medium: 16
- Large: 18
- ExtraLarge: 20
**Previous Sizes**
**Updated Sizes**

Increase global font sizes for iOS

---

SafeAuthenticator.Android/MainActivity.cs
SafeAuthenticator.iOS/Helpers/CustomScrollViewRenderer.cs
SafeAuthenticator.iOS/SafeAuthenticator.iOS.csproj
SafeAuthenticator/Controls/CustomScrollView.cs
SafeAuthenticator/Views/CreateAcctPage.xaml
SafeAuthenticator/Views/LoginPage.xaml
SafeAuthenticator/Views/LoginPage.xaml.cs

Fixes #60 
The page is to be scrollable when the keyboard is displayed on the screen
- On iOS: Create a CustomScrollView, such that initially the scrollView for the page is disabled and using the `Entry`'s `Focused` and `Unfocused` events we can enable/disable the scroll. 
- On Android: Resize the window using `SetSoftInputMode` (we do not require a custom control here, since by default only if the contents exceed the view scroll is enabled)

Enable scroll when keyboard is displayed

---

SafeAuthenticator.Android/Helpers/AndroidNativeProgressDialogService.cs
SafeAuthenticator.iOS/Helpers/AppleNativeProgressDialogService.cs
SafeAuthenticator/Controls/INativeProgressDialogService.cs

Fixes #86 
When the back button is clicked the current activity is destroyed and when we reopen the app a new activity is created. But the `ProgressDialog` object is still referring to old activity, to fix this declare the `ProgressDialog` object as a local variable of `ShowNativeDialog` and dispose it at the end.
Also, the `Dismiss()` method is not required.

Update NativeProgressDialog on Android and iOS

---

SafeAuthenticator/ViewModels/CreateAcctViewModel.cs

fixes #81 
-  Add a condition to check the secret and confirm secret is matching, if not set the error message "Secret doesn't match".
- Add a condition to check the password and confirm password is matching, if not set the error message "password doesn't match".
- Check for the secret/password strength after the confirm field  check.

Display error message if secret/password "confirm" fields don't match

---

SafeAuthenticator.Android/Helpers/MaterialEntryRenderer.cs
SafeAuthenticator/Controls/CreateAcctPage/CreateAcctStep1.xaml
SafeAuthenticator/Views/TutorialPage.xaml

fixes#84
- Add the padding for the `Control.EditText.SetPadding()` in top and bottom.
- Since the padding in Control.EditText.PaddingTop is large, divided it by 2.

Add padding between Invitation token label and the text field

---

SafeAuthenticator/Helpers/Constants.cs
SafeAuthenticator/Services/AuthService.cs
SafeAuthenticator/ViewModels/SettingsViewModel.cs
SafeAuthenticator/Views/SettingsPage.xaml.cs

Fixes #56 
When the auto-reconnect switch is toggled on display an alert with the following message `Enable this feature to automatically reconnect to the network. Your credentials will be securely stored on your device. Logging out will clear the credentials from memory.` Store the credentials in secure storage only if the user accepts this.

Provide additional information for auto-reconnect

---

SafeAuthenticator/App.xaml
SafeAuthenticator/Controls/CreateAcctPage/CreateAcctStep2.xaml
SafeAuthenticator/Controls/CreateAcctPage/CreateAcctStep3.xaml
SafeAuthenticator/Views/LoginPage.xaml
SafeAuthenticator/Views/RequestDetailPage.xaml

fixes#100
- Add padding between text fields in login page and create account page.
- Add a color to differentiate app info from permissions list in the RequestDetailPage.
**screenshots**
Android:
iOS

Adjust padding, color and size (UI fix)

---

SafeAuthenticator/ViewModels/RequestDetailViewModel.cs
SafeAuthenticator/Views/RequestDetailPage.xaml
SafeAuthenticator/Views/RequestDetailPage.xaml.cs

Fixes #98
Instead of using an `Onclick` event on the `InfoIcon` to display the `ID`, `Vendor` and resizing the popup, perform the same operation on the `ViewModel`. This is done to avoid altering a particular property in the code behind as well as in the ViewModel

Authorization popup height not consistent

---

SafeAuthenticator/App.xaml.cs
SafeAuthenticator/Helpers/MessengerConstants.cs
SafeAuthenticator/Services/AuthService.cs
SafeAuthenticator/Views/LoginPage.xaml.cs

Fixes #99 
If authorisation is sent to the authenticator before login we display a popup, have two options on the popup `login` and `Cancel`. If the user is present on the `CreateAcctPage`  redirect them to the login page

Update the popup displayed when authorizing apps before login

---

SafeAuthenticator/Controls/CreateAcctPage/CreateAcctStep2.xaml
SafeAuthenticator/Controls/CreateAcctPage/CreateAcctStep3.xaml
SafeAuthenticator/Helpers/Constants.cs
SafeAuthenticator/ViewModels/AppInfoViewModel.cs
SafeAuthenticator/ViewModels/CreateAcctViewModel.cs
SafeAuthenticator/Views/CreateAcctPage.xaml
SafeAuthenticator/Views/LoginPage.xaml
SafeAuthenticator/Views/RequestDetailPage.xaml

fixes#101 #102 #103
- Textual change for the pop-ups
- Check clipboard string in the invitation token entry using `IsNullOrWhiteSpace` before pasting it.
- Show the Secret/Password strength error message under Secret/Password field 
- create a bindable property `AcctSecretStrengthErrorMsg` for Secret
- create a bindable property `AcctPasswordStrengthErrorMsg` for Password
- Adjust padding in createaccountpage and loginpage

Texual change in CreateAccount/Login Page and Pop-ups  

---

SafeAuthenticator.Android/Helpers/AppHandler.cs
SafeAuthenticator.iOS/Helpers/AppHandler.cs
SafeAuthenticator/Helpers/Utilities.cs

Bug Fixes:
- The [OpenUrl](https://docs.microsoft.com/en-us/dotnet/api/uikit.uiapplication.openurl?view=xamarin-ios-sdk-12) API returns true if the URL was successfully opened else return false. 
- Incorrect container name displayed when an invalid container is requested.
- Add intent flag to start an activity from a non-activity context

fix/SafeAuth: bug fixes

---

CakeScripts/IOSTest.cake
CakeScripts/NativeLibs.cake
README.md

- Updated README
- Updated Simulator to use iOS 12.1

chore/bindings: update to use safe_authenticator v0.9.1 libs

---

.gitignore
SafeAuthenticator.iOS/Info.plist

**Change:**
Updated iOS build to target universal devices previously it was set to iPhone/iPad and was not using full device screen. This PR will fix that, though some changes to the UI may be needed which will be addressed in a separate PR.
**Other Changes:**
Updated `gitignore` file to ignore mfractor (VS extension) files.
**Before:**
**After:**

fix/iOS: Update iOS build from iPhone/iPad to universal

---

SafeAuthenticator/Services/VaultConnectionFileManager.cs
SafeAuthenticator/ViewModels/VaultConnectionFileViewModel.cs

**Changes:** 
- Use alert instead of an action sheet
- Disable selection when use choose cancel
- Delete default connection file if the active file is deleted

fix/vaultconnection: delete default file if deleting the active file
